# LAB 1:  BÀI THỰC HÀNH THAO TÁC DỮ LIỆU

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("dulieuxettuyendaihoc.csv")

df.head()

## 1. Xác định và phân loại dữ liệu định tính và định lượng

In [3]:
bien_dinh_tinh = df.select_dtypes(include=["object"]).columns.tolist()

# Thêm DT vào định tính nếu có
if "DT" in df.columns and "DT" not in bien_dinh_tinh:
    bien_dinh_tinh.append("DT")

bien_dinh_luong = df.select_dtypes(include=["int64", "float64"]).columns.tolist()

# Loại STT và DT khỏi định lượng
for cot in ["STT", "DT"]:
    if cot in bien_dinh_luong:
        bien_dinh_luong.remove(cot)

print("Các biến định tính:")
print(bien_dinh_tinh)

print("\nCác biến định lượng:")
print(bien_dinh_luong)

Các biến định tính:
['GT', 'KV', 'KT', 'DT']

Các biến định lượng:
['T1', 'L1', 'H1', 'S1', 'V1', 'X1', 'D1', 'N1', 'T2', 'L2', 'H2', 'S2', 'V2', 'X2', 'D2', 'N2', 'T3', 'L3', 'H3', 'S3', 'V3', 'X3', 'D3', 'N3', 'T4', 'L4', 'H4', 'S4', 'V4', 'X4', 'D4', 'N4', 'T5', 'L5', 'H5', 'S5', 'V5', 'X5', 'D5', 'N5', 'T6', 'L6', 'H6', 'S6', 'V6', 'X6', 'D6', 'N6', 'DH1', 'DH2', 'DH3']

## 2. Định nghĩa các thang đo phù hợp cho từng biến số

In [5]:
thang_do = {}

for cot in df.columns:
    # STT là số thứ tự, dùng để định danh
    if cot == "STT":
        thang_do[cot] = "Định danh"
    
    # GT: Giới tính, DT: Dân tộc, KT: Khối thi
    elif cot in ["GT", "DT", "KT"]:
        thang_do[cot] = "Định danh"
    
    # KV: Khu vực, có mức độ ưu tiên nên xem là thứ bậc
    elif cot == "KV":
        thang_do[cot] = "Thứ bậc"
    
    # Các cột còn lại là điểm số
    else:
        thang_do[cot] = "Tỉ lệ"

# Chuyển thành bảng để xem cho đẹp
bang_thang_do = pd.DataFrame({
    "Biến": list(thang_do.keys()),
    "Thang đo": list(thang_do.values())
})

bang_thang_do

   Biến   Thang đo
0   STT  Định danh
1    T1      Tỉ lệ
2    L1      Tỉ lệ
3    H1      Tỉ lệ
4    S1      Tỉ lệ
5    V1      Tỉ lệ
6    X1      Tỉ lệ
7    D1      Tỉ lệ
8    N1      Tỉ lệ
9    T2      Tỉ lệ
10   L2      Tỉ lệ
11   H2      Tỉ lệ
12   S2      Tỉ lệ
13   V2      Tỉ lệ
14   X2      Tỉ lệ
15   D2      Tỉ lệ
16   N2      Tỉ lệ
17   T3      Tỉ lệ
18   L3      Tỉ lệ
19   H3      Tỉ lệ
20   S3      Tỉ lệ
21   V3      Tỉ lệ
22   X3      Tỉ lệ
23   D3      Tỉ lệ
24   N3      Tỉ lệ
25   T4      Tỉ lệ
26   L4      Tỉ lệ
27   H4      Tỉ lệ
28   S4      Tỉ lệ
29   V4      Tỉ lệ
30   X4      Tỉ lệ
31   D4      Tỉ lệ
32   N4      Tỉ lệ
33   T5      Tỉ lệ
34   L5      Tỉ lệ
35   H5      Tỉ lệ
36   S5      Tỉ lệ
37   V5      Tỉ lệ
38   X5      Tỉ lệ
39   D5      Tỉ lệ
40   N5      Tỉ lệ
41   T6      Tỉ lệ
42   L6      Tỉ lệ
43   H6      Tỉ lệ
44   S6      Tỉ lệ
45   V6      Tỉ lệ
46   X6      Tỉ lệ
47   D6      Tỉ lệ
48   N6      Tỉ lệ
49   GT  Định danh
50   DT  Định danh
51   KV    Thứ bậc
52  DH1      Tỉ lệ
53  DH2      Tỉ lệ
54  DH3      Tỉ lệ
55   KT  Định danh

## 3. Sử dụng Python để tải dữ liệu lên chương trình và in ra màn hình 10 dòng đầu tiên và 10 dòng cuối cùng

In [6]:
# Câu 3: Tải dữ liệu và in ra 10 dòng đầu tiên, 10 dòng cuối cùng

import pandas as pd

# Đọc file dữ liệu
df = pd.read_csv("dulieuxettuyendaihoc.csv")

# In 10 dòng đầu tiên
print("10 dòng đầu tiên:")
display(df.head(10))

# In 10 dòng cuối cùng
print("10 dòng cuối cùng:")
display(df.tail(10))

10 dòng đầu tiên:

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,6.6,7.6,5.9,F,NaN,2NT,3.25,3.25,4.50,A1
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,6.6,6.1,4.4,M,NaN,1,6.00,4.00,3.50,C
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,7.9,8.1,4.6,M,NaN,1,5.00,6.75,4.00,C
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,7.1,7.3,7.4,M,NaN,1,4.25,4.25,5.25,D1
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.1,7.5,7.2,M,NaN,2NT,4.25,4.50,5.00,A
5,6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,...,5.7,8.0,7.8,M,NaN,1,1.50,4.00,6.00,D1
6,7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,...,6.6,6.0,6.0,F,NaN,2,6.50,6.75,5.25,C
7,8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,...,7.1,6.8,7.0,F,NaN,2,3.75,4.50,4.25,D1
8,9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,...,9.1,7.9,6.1,F,NaN,1,3.50,3.50,6.75,D1
9,10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,...,6.4,6.1,7.8,F,NaN,1,4.00,4.75,5.50,D1

10 dòng cuối cùng:

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
90,91,8.1,7.7,9.1,8.5,6.1,8.6,8.8,7.3,8.8,...,8.3,8.7,7.8,M,NaN,2,6.25,4.00,6.50,A
91,92,7.8,6.5,6.7,5.4,6.2,4.8,5.9,4.4,8.9,...,7.2,7.4,7.0,M,NaN,2NT,4.75,4.75,4.50,A
92,93,5.0,6.6,6.5,7.2,5.8,6.7,6.4,6.0,6.8,...,5.9,6.7,5.8,M,NaN,1,3.25,5.25,4.25,A
93,94,5.2,5.2,6.8,7.9,6.6,8.9,7.6,5.3,6.8,...,8.7,7.8,5.0,M,NaN,1,3.50,4.25,5.00,A
94,95,5.8,5.9,7.6,6.1,5.3,8.1,6.1,5.0,6.4,...,7.3,6.8,5.3,M,NaN,1,4.25,2.50,4.75,A
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,6.3,6.1,6.2,F,NaN,1,5.25,1.50,6.25,C
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,7.9,7.5,4.4,F,NaN,1,5.25,3.75,4.75,C
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,9.6,8.4,5.8,M,NaN,2NT,7.00,8.00,4.00,C
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,6.6,5.2,5.9,M,NaN,1,5.00,3.50,5.50,C
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.6,6.6,5.8,M,NaN,2NT,5.25,2.50,4.25,C

##  Câu 4: Thống kê dữ liệu thiếu cho cột dân tộc DT

In [8]:
# Mặc định thiếu thì điền giá trị 0

# Lập bảng tần số và tần suất trước khi xử lý
tan_so_DT = df["DT"].value_counts(dropna=False)
tan_suat_DT = df["DT"].value_counts(dropna=False, normalize=True) * 100

bang_thong_ke_DT = pd.DataFrame({
    "Tần số": tan_so_DT,
    "Tần suất (%)": tan_suat_DT
})

print("BẢNG TẦN SỐ, TẦN SUẤT CỦA CỘT DT TRƯỚC KHI XỬ LÝ")
display(bang_thong_ke_DT)

# Thống kê dữ liệu thiếu
so_luong_thieu_DT = df["DT"].isnull().sum()
ti_le_thieu_DT = df["DT"].isnull().mean() * 100

print("Số lượng dữ liệu thiếu của cột DT:", so_luong_thieu_DT)
print("Tỉ lệ dữ liệu thiếu của cột DT (%):", ti_le_thieu_DT)

# Khảo sát dữ liệu riêng biệt bằng unique
du_lieu_rieng_biet_DT = df["DT"].unique()
so_du_lieu_rieng_biet_DT = df["DT"].nunique(dropna=True)

print("Các dữ liệu riêng biệt của cột DT:")
print(du_lieu_rieng_biet_DT)

print("Số lượng dữ liệu riêng biệt của cột DT:", so_du_lieu_rieng_biet_DT)

# Thay thế dữ liệu thiếu bằng giá trị 0
df["DT"] = df["DT"].fillna(0)

print("\nSAU KHI ĐIỀN DỮ LIỆU THIẾU BẰNG 0")
print("Số lượng dữ liệu thiếu của cột DT:", df["DT"].isnull().sum())

# Lập lại bảng tần số và tần suất sau khi xử lý
tan_so_DT_sau = df["DT"].value_counts(dropna=False)
tan_suat_DT_sau = df["DT"].value_counts(dropna=False, normalize=True) * 100

bang_thong_ke_DT_sau = pd.DataFrame({
    "Tần số": tan_so_DT_sau,
    "Tần suất (%)": tan_suat_DT_sau
})

print("BẢNG TẦN SỐ, TẦN SUẤT CỦA CỘT DT SAU KHI XỬ LÝ")
display(bang_thong_ke_DT_sau)

BẢNG TẦN SỐ, TẦN SUẤT CỦA CỘT DT TRƯỚC KHI XỬ LÝ

     Tần số  Tần suất (%)
DT
0.0      97          97.0
1.0       2           2.0
6.0       1           1.0

Số lượng dữ liệu thiếu của cột DT: 0
Tỉ lệ dữ liệu thiếu của cột DT (%): 0.0
Các dữ liệu riêng biệt của cột DT:
[0. 1. 6.]
Số lượng dữ liệu riêng biệt của cột DT: 3

SAU KHI ĐIỀN DỮ LIỆU THIẾU BẰNG 0
Số lượng dữ liệu thiếu của cột DT: 0
BẢNG TẦN SỐ, TẦN SUẤT CỦA CỘT DT SAU KHI XỬ LÝ

     Tần số  Tần suất (%)
DT
0.0      97          97.0
1.0       2           2.0
6.0       1           1.0

## 5. Thống kê dữ liệu thiếu cho biến T1 và hiệu chỉnh dữ liệu, lưu ý việc thay thế dữ liệu thiếu sử dụng phương pháp Mean.

In [9]:
# Hiệu chỉnh dữ liệu thiếu bằng phương pháp điền giá trị Mean

# 1. Lập bảng tần số và tần suất trước khi xử lý
tan_so_T1 = df["T1"].value_counts(dropna=False)
tan_suat_T1 = df["T1"].value_counts(dropna=False, normalize=True) * 100

bang_thong_ke_T1 = pd.DataFrame({
    "Tần số": tan_so_T1,
    "Tần suất (%)": tan_suat_T1
})

print("BẢNG TẦN SỐ, TẦN SUẤT CỦA CỘT T1 TRƯỚC KHI XỬ LÝ")
display(bang_thong_ke_T1)

# 2. Thống kê dữ liệu thiếu
so_luong_thieu_T1 = df["T1"].isnull().sum()
ti_le_thieu_T1 = df["T1"].isnull().mean() * 100

print("Số lượng dữ liệu thiếu của cột T1:", so_luong_thieu_T1)
print("Tỉ lệ dữ liệu thiếu của cột T1 (%):", ti_le_thieu_T1)

# 3. Khảo sát dữ liệu riêng biệt bằng unique
du_lieu_rieng_biet_T1 = df["T1"].unique()
so_du_lieu_rieng_biet_T1 = df["T1"].nunique(dropna=True)

print("Các dữ liệu riêng biệt của cột T1:")
print(du_lieu_rieng_biet_T1)

print("Số lượng dữ liệu riêng biệt của cột T1:", so_du_lieu_rieng_biet_T1)

# 4. Tính giá trị Mean của T1
mean_T1 = df["T1"].mean()

print("Giá trị Mean của cột T1:", mean_T1)

# 5. Thay thế dữ liệu thiếu bằng giá trị Mean
df["T1"] = df["T1"].fillna(mean_T1)

print("\nSAU KHI ĐIỀN DỮ LIỆU THIẾU BẰNG MEAN")
print("Số lượng dữ liệu thiếu của cột T1:", df["T1"].isnull().sum())

# 6. Lập lại bảng tần số và tần suất sau khi xử lý
tan_so_T1_sau = df["T1"].value_counts(dropna=False)
tan_suat_T1_sau = df["T1"].value_counts(dropna=False, normalize=True) * 100

bang_thong_ke_T1_sau = pd.DataFrame({
    "Tần số": tan_so_T1_sau,
    "Tần suất (%)": tan_suat_T1_sau
})

print("BẢNG TẦN SỐ, TẦN SUẤT CỦA CỘT T1 SAU KHI XỬ LÝ")
display(bang_thong_ke_T1_sau)

# 7. Kết luận
print("\nKết luận:")
print("Đã thống kê dữ liệu thiếu của cột T1.")
print("Dữ liệu thiếu của cột T1 đã được thay thế bằng giá trị Mean.")

BẢNG TẦN SỐ, TẦN SUẤT CỦA CỘT T1 TRƯỚC KHI XỬ LÝ

     Tần số  Tần suất (%)
T1
5.2       5           5.0
7.3       5           5.0
5.3       5           5.0
6.0       4           4.0
7.2       4           4.0
7.9       4           4.0
4.9       3           3.0
5.4       3           3.0
5.0       3           3.0
8.2       3           3.0
6.5       3           3.0
5.5       3           3.0
6.3       3           3.0
8.8       2           2.0
7.1       2           2.0
8.3       2           2.0
6.4       2           2.0
3.6       2           2.0
8.1       2           2.0
6.6       2           2.0
5.6       2           2.0
5.7       2           2.0
5.8       2           2.0
3.0       2           2.0
5.1       2           2.0
9.3       1           1.0
3.9       1           1.0
2.5       1           1.0
2.8       1           1.0
2.4       1           1.0
3.4       1           1.0
4.3       1           1.0
4.4       1           1.0
4.7       1           1.0
4.5       1           1.0
2.6       1           1.0
7.6       1           1.0
6.7       1           1.0
6.9       1           1.0
6.1       1           1.0
7.0       1           1.0
6.2       1           1.0
4.6       1           1.0
4.2       1           1.0
7.5       1           1.0
4.8       1           1.0
5.9       1           1.0
8.4       1           1.0
7.8       1           1.0
8.6       1           1.0
3.7       1           1.0
2.7       1           1.0
4.1       1           1.0

Số lượng dữ liệu thiếu của cột T1: 0
Tỉ lệ dữ liệu thiếu của cột T1 (%): 0.0
Các dữ liệu riêng biệt của cột T1:
[7.2 5.4 5.6 6.6 6.  9.3 2.8 8.3 6.5 7.3 5.2 7.9 4.9 7.1 2.5 8.8 8.2 3.9
 5.  5.3 2.4 3.6 8.1 6.3 4.5 7.6 2.6 6.4 4.7 3.4 4.4 4.3 7.  6.1 6.9 6.7
 5.5 6.2 7.5 3.  5.1 4.6 5.8 4.2 4.8 5.7 5.9 8.4 7.8 8.6 3.7 2.7 4.1]
Số lượng dữ liệu riêng biệt của cột T1: 53
Giá trị Mean của cột T1: 5.946000000000001

SAU KHI ĐIỀN DỮ LIỆU THIẾU BẰNG MEAN
Số lượng dữ liệu thiếu của cột T1: 0
BẢNG TẦN SỐ, TẦN SUẤT CỦA CỘT T1 SAU KHI XỬ LÝ

     Tần số  Tần suất (%)
T1
5.2       5           5.0
7.3       5           5.0
5.3       5           5.0
6.0       4           4.0
7.2       4           4.0
7.9       4           4.0
4.9       3           3.0
5.4       3           3.0
5.0       3           3.0
8.2       3           3.0
6.5       3           3.0
5.5       3           3.0
6.3       3           3.0
8.8       2           2.0
7.1       2           2.0
8.3       2           2.0
6.4       2           2.0
3.6       2           2.0
8.1       2           2.0
6.6       2           2.0
5.6       2           2.0
5.7       2           2.0
5.8       2           2.0
3.0       2           2.0
5.1       2           2.0
9.3       1           1.0
3.9       1           1.0
2.5       1           1.0
2.8       1           1.0
2.4       1           1.0
3.4       1           1.0
4.3       1           1.0
4.4       1           1.0
4.7       1           1.0
4.5       1           1.0
2.6       1           1.0
7.6       1           1.0
6.7       1           1.0
6.9       1           1.0
6.1       1           1.0
7.0       1           1.0
6.2       1           1.0
4.6       1           1.0
4.2       1           1.0
7.5       1           1.0
4.8       1           1.0
5.9       1           1.0
8.4       1           1.0
7.8       1           1.0
8.6       1           1.0
3.7       1           1.0
2.7       1           1.0
4.1       1           1.0

Kết luận:
Đã thống kê dữ liệu thiếu của cột T1.
Dữ liệu thiếu của cột T1 đã được thay thế bằng giá trị Mean.

## 6. Hãy thực hiện xử lý lần lượt tất cả dữ liệu thiếu cho các biến về điểm số còn lại.

In [10]:
# Phương pháp: điền dữ liệu thiếu bằng giá trị Mean của từng cột

# Danh sách tất cả các cột điểm số
cot_diem = [
    "T1", "L1", "H1", "S1", "V1", "X1", "D1", "N1",
    "T2", "L2", "H2", "S2", "V2", "X2", "D2", "N2",
    "T3", "L3", "H3", "S3", "V3", "X3", "D3", "N3",
    "T4", "L4", "H4", "S4", "V4", "X4", "D4", "N4",
    "T5", "L5", "H5", "S5", "V5", "X5", "D5", "N5",
    "T6", "L6", "H6", "S6", "V6", "X6", "D6", "N6",
    "DH1", "DH2", "DH3"
]

# Lọc lại các cột có trong DataFrame để tránh lỗi
cot_diem = [cot for cot in cot_diem if cot in df.columns]

# Thống kê dữ liệu thiếu trước khi xử lý
bang_thieu_truoc = pd.DataFrame({
    "Cột": cot_diem,
    "Số lượng thiếu": [df[cot].isnull().sum() for cot in cot_diem],
    "Tỉ lệ thiếu (%)": [df[cot].isnull().mean() * 100 for cot in cot_diem],
    "Số giá trị riêng biệt": [df[cot].nunique(dropna=True) for cot in cot_diem]
})

print("BẢNG THỐNG KÊ DỮ LIỆU THIẾU TRƯỚC KHI XỬ LÝ")
display(bang_thieu_truoc)

# Thay thế dữ liệu thiếu bằng Mean cho từng cột điểm
for cot in cot_diem:
    mean_cot = df[cot].mean()
    df[cot] = df[cot].fillna(mean_cot)

# Thống kê dữ liệu thiếu sau khi xử lý
bang_thieu_sau = pd.DataFrame({
    "Cột": cot_diem,
    "Số lượng thiếu": [df[cot].isnull().sum() for cot in cot_diem],
    "Tỉ lệ thiếu (%)": [df[cot].isnull().mean() * 100 for cot in cot_diem],
    "Số giá trị riêng biệt": [df[cot].nunique(dropna=True) for cot in cot_diem]
})

print("BẢNG THỐNG KÊ DỮ LIỆU THIẾU SAU KHI XỬ LÝ")
display(bang_thieu_sau)

# Kiểm tra tổng số dữ liệu thiếu trong các cột điểm
print("Tổng số dữ liệu thiếu còn lại trong các cột điểm:", df[cot_diem].isnull().sum().sum())

print("\nKết luận:")
print("Đã xử lý dữ liệu thiếu cho tất cả các biến điểm số bằng phương pháp điền giá trị Mean.")

BẢNG THỐNG KÊ DỮ LIỆU THIẾU TRƯỚC KHI XỬ LÝ

    Cột  Số lượng thiếu  Tỉ lệ thiếu (%)  Số giá trị riêng biệt
0    T1               0              0.0                     53
1    L1               0              0.0                     42
2    H1               0              0.0                     45
3    S1               0              0.0                     43
4    V1               0              0.0                     39
5    X1               0              0.0                     44
6    D1               0              0.0                     42
7    N1               0              0.0                     45
8    T2               0              0.0                     49
9    L2               0              0.0                     42
10   H2               0              0.0                     45
11   S2               0              0.0                     44
12   V2               0              0.0                     38
13   X2               0              0.0                     38
14   D2               0              0.0                     37
15   N2               0              0.0                     46
16   T3               0              0.0                     51
17   L3               0              0.0                     43
18   H3               0              0.0                     47
19   S3               0              0.0                     39
20   V3               0              0.0                     38
21   X3               0              0.0                     44
22   D3               0              0.0                     39
23   N3               0              0.0                     46
24   T4               0              0.0                     48
25   L4               0              0.0                     43
26   H4               0              0.0                     46
27   S4               0              0.0                     41
28   V4               0              0.0                     38
29   X4               0              0.0                     40
30   D4               0              0.0                     37
31   N4               0              0.0                     45
32   T5               0              0.0                     47
33   L5               0              0.0                     42
34   H5               0              0.0                     42
35   S5               0              0.0                     38
36   V5               0              0.0                     35
37   X5               0              0.0                     45
38   D5               0              0.0                     42
39   N5               0              0.0                     42
40   T6               0              0.0                     45
41   L6               0              0.0                     40
42   H6               0              0.0                     39
43   S6               0              0.0                     40
44   V6               0              0.0                     39
45   X6               0              0.0                     41
46   D6               0              0.0                     35
47   N6               0              0.0                     38
48  DH1               0              0.0                     24
49  DH2               0              0.0                     21
50  DH3               0              0.0                     18

BẢNG THỐNG KÊ DỮ LIỆU THIẾU SAU KHI XỬ LÝ

    Cột  Số lượng thiếu  Tỉ lệ thiếu (%)  Số giá trị riêng biệt
0    T1               0              0.0                     53
1    L1               0              0.0                     42
2    H1               0              0.0                     45
3    S1               0              0.0                     43
4    V1               0              0.0                     39
5    X1               0              0.0                     44
6    D1               0              0.0                     42
7    N1               0              0.0                     45
8    T2               0              0.0                     49
9    L2               0              0.0                     42
10   H2               0              0.0                     45
11   S2               0              0.0                     44
12   V2               0              0.0                     38
13   X2               0              0.0                     38
14   D2               0              0.0                     37
15   N2               0              0.0                     46
16   T3               0              0.0                     51
17   L3               0              0.0                     43
18   H3               0              0.0                     47
19   S3               0              0.0                     39
20   V3               0              0.0                     38
21   X3               0              0.0                     44
22   D3               0              0.0                     39
23   N3               0              0.0                     46
24   T4               0              0.0                     48
25   L4               0              0.0                     43
26   H4               0              0.0                     46
27   S4               0              0.0                     41
28   V4               0              0.0                     38
29   X4               0              0.0                     40
30   D4               0              0.0                     37
31   N4               0              0.0                     45
32   T5               0              0.0                     47
33   L5               0              0.0                     42
34   H5               0              0.0                     42
35   S5               0              0.0                     38
36   V5               0              0.0                     35
37   X5               0              0.0                     45
38   D5               0              0.0                     42
39   N5               0              0.0                     42
40   T6               0              0.0                     45
41   L6               0              0.0                     40
42   H6               0              0.0                     39
43   S6               0              0.0                     40
44   V6               0              0.0                     39
45   X6               0              0.0                     41
46   D6               0              0.0                     35
47   N6               0              0.0                     38
48  DH1               0              0.0                     24
49  DH2               0              0.0                     21
50  DH3               0              0.0                     18

Tổng số dữ liệu thiếu còn lại trong các cột điểm: 0

Kết luận:
Đã xử lý dữ liệu thiếu cho tất cả các biến điểm số bằng phương pháp điền giá trị Mean.

## Câu 7: Tạo biến TBM1, TBM2, TBM3

In [16]:
# TBM1: điểm trung bình lớp 10
# TBM2: điểm trung bình lớp 11
# TBM3: điểm trung bình lớp 12

def tinh_tbm_hoc_ky(ky):
    return (
        df[f"T{ky}"] * 2 +
        df[f"L{ky}"] +
        df[f"H{ky}"] +
        df[f"S{ky}"] +
        df[f"V{ky}"] * 2 +
        df[f"X{ky}"] +
        df[f"D{ky}"] +
        df[f"N{ky}"]
    ) / 10

# Tính điểm trung bình từng học kỳ
tbm_hk1 = tinh_tbm_hoc_ky(1)
tbm_hk2 = tinh_tbm_hoc_ky(2)
tbm_hk3 = tinh_tbm_hoc_ky(3)
tbm_hk4 = tinh_tbm_hoc_ky(4)
tbm_hk5 = tinh_tbm_hoc_ky(5)
tbm_hk6 = tinh_tbm_hoc_ky(6)

# Tính điểm trung bình từng năm
# HK2 nhân hệ số 2
df["TBM1"] = ((tbm_hk1 + tbm_hk2 * 2) / 3).round(2)
df["TBM2"] = ((tbm_hk3 + tbm_hk4 * 2) / 3).round(2)
df["TBM3"] = ((tbm_hk5 + tbm_hk6 * 2) / 3).round(2)

print("KẾT QUẢ TẠO BIẾN TBM1, TBM2, TBM3")
display(df[["TBM1", "TBM2", "TBM3"]].head(10))

print("Thống kê mô tả của TBM1, TBM2, TBM3:")
display(df[["TBM1", "TBM2", "TBM3"]].describe())

print("Kết luận: Đã tạo thành công 3 biến TBM1, TBM2, TBM3 cho lớp 10, 11, 12.")

KẾT QUẢ TẠO BIẾN TBM1, TBM2, TBM3

   TBM1  TBM2  TBM3
0  7.36  6.86  6.85
1  5.21  5.08  4.91
2  5.51  5.09  5.63
3  5.54  5.65  6.48
4  6.41  6.52  6.63
5  8.35  8.01  7.58
6  5.37  5.82  5.81
7  6.85  6.86  6.98
8  6.56  7.03  7.33
9  7.10  6.87  6.97

Thống kê mô tả của TBM1, TBM2, TBM3:

             TBM1        TBM2        TBM3
count  100.000000  100.000000  100.000000
mean     6.295200    6.436500    6.541200
std      0.927288    0.861998    0.753696
min      4.400000    4.510000    4.770000
25%      5.492500    5.745000    6.077500
50%      6.360000    6.615000    6.660000
75%      7.045000    7.052500    7.035000
max      8.350000    8.100000    8.140000

Kết luận: Đã tạo thành công 3 biến TBM1, TBM2, TBM3 cho lớp 10, 11, 12.

## 8. Tạo các biến xếp loại XL1, XL2 và XL3 dựa trên TBM1,TBM2 và TBM3 cho từng năm lớp 10, 11, 12

In [17]:
# Hàm xếp loại học lực
def xep_loai(tbm):
    if tbm < 5.0:
        return "Y"      # Yếu
    elif tbm < 6.5:
        return "TB"     # Trung bình
    elif tbm < 8.0:
        return "K"      # Khá
    elif tbm < 9.0:
        return "G"      # Giỏi
    else:
        return "XS"     # Xuất sắc

# Tạo các biến xếp loại
df["XL1"] = df["TBM1"].apply(xep_loai)
df["XL2"] = df["TBM2"].apply(xep_loai)
df["XL3"] = df["TBM3"].apply(xep_loai)

# Hiển thị kết quả 10 dòng đầu
print("KẾT QUẢ TẠO BIẾN XL1, XL2, XL3")
display(df[["TBM1", "XL1", "TBM2", "XL2", "TBM3", "XL3"]].head(10))

# Thống kê tần số xếp loại
print("Tần số xếp loại XL1:")
display(df["XL1"].value_counts())

print("Tần số xếp loại XL2:")
display(df["XL2"].value_counts())

print("Tần số xếp loại XL3:")
display(df["XL3"].value_counts())

print("Kết luận: Đã tạo thành công các biến xếp loại XL1, XL2, XL3.")

KẾT QUẢ TẠO BIẾN XL1, XL2, XL3

   TBM1 XL1  TBM2 XL2  TBM3 XL3
0  7.36   K  6.86   K  6.85   K
1  5.21  TB  5.08  TB  4.91   Y
2  5.51  TB  5.09  TB  5.63  TB
3  5.54  TB  5.65  TB  6.48  TB
4  6.41  TB  6.52   K  6.63   K
5  8.35   G  8.01   G  7.58   K
6  5.37  TB  5.82  TB  5.81  TB
7  6.85   K  6.86   K  6.98   K
8  6.56   K  7.03   K  7.33   K
9  7.10   K  6.87   K  6.97   K

Tần số xếp loại XL1:

XL1
TB    51
K     40
Y      6
G      3
Name: count, dtype: int64

Tần số xếp loại XL2:

XL2
K     50
TB    44
G      3
Y      3
Name: count, dtype: int64

Tần số xếp loại XL3:

XL3
K     55
TB    41
Y      2
G      2
Name: count, dtype: int64

Kết luận: Đã tạo thành công các biến xếp loại XL1, XL2, XL3.

## 9. Tạo các biến US_TBM1, US_TBM2 và US_TBM3 để chuyển điểm trung bình các năm lớp 10, 11 và 12 từ thang điểm 10 của Việt Nam sang thang điểm 4 của Mỹ. Sử dụng phương pháp Min-Max Normalization

In [18]:
# Chuyển điểm trung bình từ thang điểm 10 sang thang điểm 4
# Công thức Min-Max Normalization:
# US_TBM = (TBM / 10) * 4

# Tạo các biến US_TBM
df["US_TBM1"] = (df["TBM1"] / 10) * 4
df["US_TBM2"] = (df["TBM2"] / 10) * 4
df["US_TBM3"] = (df["TBM3"] / 10) * 4

# Làm tròn 2 chữ số thập phân
df["US_TBM1"] = df["US_TBM1"].round(2)
df["US_TBM2"] = df["US_TBM2"].round(2)
df["US_TBM3"] = df["US_TBM3"].round(2)

# Hiển thị kết quả 10 dòng đầu
print("KẾT QUẢ TẠO BIẾN US_TBM1, US_TBM2, US_TBM3")
display(df[[
    "TBM1", "US_TBM1",
    "TBM2", "US_TBM2",
    "TBM3", "US_TBM3"
]].head(10))

# Thống kê mô tả các biến mới
print("THỐNG KÊ MÔ TẢ CÁC BIẾN US_TBM")
display(df[["US_TBM1", "US_TBM2", "US_TBM3"]].describe())

print("Kết luận: Đã tạo thành công các biến US_TBM1, US_TBM2, US_TBM3 bằng phương pháp Min-Max Normalization.")

KẾT QUẢ TẠO BIẾN US_TBM1, US_TBM2, US_TBM3

   TBM1  US_TBM1  TBM2  US_TBM2  TBM3  US_TBM3
0  7.36     2.94  6.86     2.74  6.85     2.74
1  5.21     2.08  5.08     2.03  4.91     1.96
2  5.51     2.20  5.09     2.04  5.63     2.25
3  5.54     2.22  5.65     2.26  6.48     2.59
4  6.41     2.56  6.52     2.61  6.63     2.65
5  8.35     3.34  8.01     3.20  7.58     3.03
6  5.37     2.15  5.82     2.33  5.81     2.32
7  6.85     2.74  6.86     2.74  6.98     2.79
8  6.56     2.62  7.03     2.81  7.33     2.93
9  7.10     2.84  6.87     2.75  6.97     2.79

THỐNG KÊ MÔ TẢ CÁC BIẾN US_TBM

         US_TBM1     US_TBM2     US_TBM3
count  100.00000  100.000000  100.000000
mean     2.51780    2.574600    2.616700
std      0.37045    0.344408    0.301391
min      1.76000    1.800000    1.910000
25%      2.19750    2.297500    2.430000
50%      2.54500    2.645000    2.665000
75%      2.81750    2.825000    2.812500
max      3.34000    3.240000    3.260000

Kết luận: Đã tạo thành công các biến US_TBM1, US_TBM2, US_TBM3 bằng phương pháp Min-Max Normalization.

## Câu 10: Tạo biến KQXT - Kết quả xét tuyển

In [14]:
# Quy tắc:
# Nếu khối A hoặc A1: điểm xét tuyển = (DH1*2 + DH2 + DH3) / 4
# Nếu khối B: điểm xét tuyển = (DH1 + DH2*2 + DH3) / 4
# Các khối còn lại: điểm xét tuyển = (DH1 + DH2 + DH3) / 3
# Nếu điểm xét tuyển >= 5 thì KQXT = 1, ngược lại KQXT = 0

def tinh_kqxt(row):
    khoi = str(row["KT"]).strip()
    dh1 = row["DH1"]
    dh2 = row["DH2"]
    dh3 = row["DH3"]
    
    if khoi in ["A", "A1"]:
        diem_xet_tuyen = (dh1 * 2 + dh2 + dh3) / 4
    elif khoi == "B":
        diem_xet_tuyen = (dh1 + dh2 * 2 + dh3) / 4
    else:
        diem_xet_tuyen = (dh1 + dh2 + dh3) / 3
    
    if diem_xet_tuyen >= 5:
        return 1
    else:
        return 0

# Tạo biến KQXT
df["KQXT"] = df.apply(tinh_kqxt, axis=1)

# Hiển thị kết quả 10 dòng đầu
print("KẾT QUẢ TẠO BIẾN KQXT")
display(df[["KT", "DH1", "DH2", "DH3", "KQXT"]].head(10))

# Thống kê tần số kết quả xét tuyển
print("Tần số kết quả xét tuyển:")
display(df["KQXT"].value_counts())

print("Kết luận: Đã tạo thành công biến KQXT.")

KẾT QUẢ TẠO BIẾN KQXT

   KT   DH1   DH2   DH3  KQXT
0  A1  3.25  3.25  4.50     0
1   C  6.00  4.00  3.50     0
2   C  5.00  6.75  4.00     1
3  D1  4.25  4.25  5.25     0
4   A  4.25  4.50  5.00     0
5  D1  1.50  4.00  6.00     0
6   C  6.50  6.75  5.25     1
7  D1  3.75  4.50  4.25     0
8  D1  3.50  3.50  6.75     0
9  D1  4.00  4.75  5.50     0

Tần số kết quả xét tuyển:

KQXT
0    88
1    12
Name: count, dtype: int64

Kết luận: Đã tạo thành công biến KQXT.

In [ ]:
df.to_csv("processed_dulieuxettuyendaihoc.csv", index=False)

print("Đã lưu file processed_dulieuxettuyendaihoc.csv")